apiVersion: v1
kind: Service
metadata:
  name: {{ include "oj-lab.fullname" . }}-platform
  labels:
    {{- include "oj-lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.platform.service.type }}
  ports:
    - port: {{ .Values.platform.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    oj-lab/application: platform
    {{- include "oj-lab.selectorLabels" . | nindent 4 }}
