{{- if .Values.platform.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oj-lab.serviceAccountName" . }}
  labels:
    {{- include "oj-lab.labels" . | nindent 4 }}
  {{- with .Values.platform.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.platform.serviceAccount.automount }}
{{- end }}
